//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int MId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> English { get; set; }
        public Nullable<int> SocialScience { get; set; }
        public Nullable<int> Science { get; set; }
        public Nullable<int> Mathematics { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
